export const emailAgent = {
  async run(input: unknown) {
    return {
      agent: "email",
      status: "ok",
      subject: "Your Mock Personalised Plan",
      body: "Thanks for your enquiry. This is a mock email response generated by the email agent.",
      summary: "Mock email payload generated.",
      input,
    };
  },
};
